export class PlacementForm {
   campaign_public_identifier: string
   public_identifier: string
   audiences_blacklisted: Array<any>
   audiences_whitelisted: Array<any>
   bid: number
   bid_type_id: any
   budget: number
   carriers: Array<any>
   cities: Array<any>
   click_cap_daily: number
   click_cap_monthly: number
   client_budget: number
   connection_types: Array<any>
   countries: Array<any>
   device_models: Array<any>
   device_types: Array<any>
   dmas: Array<any>
   end_date: string
   gender_id: number
   impression_cap_daily: number
   impression_cap_hourly: number
   impression_cap_monthly: number
   is_pacing_enabled: boolean
   location_radius_target: number
   location_targets: Array<any>
   max_bid_amount: number
   media_fee_percent: number
   minimum_viewability_target: null
   name: string
   os_versions: Array<any>
   placement_optimization_goal_id: number
   placement_optimization_goal_value: number
   postal_codes: Array<any>
   regions: Array<any>
   reward_target: string
   start_date: string
   status: string
   traffic_type_target: string
   file: File
   categories_blacklisted: string[]
   categories_whitelisted: string[]
   publisher_lists_whitelisted: string[]
   publisher_lists_blacklisted: string[]
}